import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def send_email(
    subject: str,
    body: str,
    smtp_server: str = "smtp.gmail.com",
    smtp_port: int = 587,
    sender_email: str = "",
    sender_password: str = "",
    recipient_email: str = "",
) -> bool:
    """Send email notification via Gmail SMTP."""
    if not all([sender_email, sender_password, recipient_email]):
        print("Email not configured — skipping notification")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = sender_email
        msg["To"] = recipient_email
        msg["Subject"] = subject

        html_body = f"""
        <html>
        <body style="font-family: 'Courier New', monospace; background: #0a0a0a; color: #00ff41; padding: 20px;">
            <pre style="white-space: pre-wrap; font-size: 14px;">{body}</pre>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)

        print(f"Email sent to {recipient_email}")
        return True

    except Exception as e:
        print(f"Email error: {e}")
        return False


def format_daily_report(summary: dict, signals: list[dict], actions: list[str]) -> str:
    """Format portfolio summary into a readable email report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        "=" * 60,
        f"  KRONOS TRADING ENGINE — DAILY REPORT",
        f"  {now}",
        "=" * 60,
        "",
        "PORTFOLIO SUMMARY",
        "-" * 40,
        f"  Cash:           ${summary['cash']:>12,.2f}",
        f"  Equity:         ${summary['equity']:>12,.2f}",
        f"  Total Value:    ${summary['total_value']:>12,.2f}",
        f"  Daily P&L:      ${summary['daily_pnl']:>12,.2f}",
        f"  Cumulative P&L: ${summary['cumulative_pnl']:>12,.2f}",
        f"  Positions:      {summary['num_positions']}",
        f"  Total Trades:   {summary['total_trades']}",
        "",
    ]

    if actions:
        lines.append("TODAY'S ACTIONS")
        lines.append("-" * 40)
        for a in actions:
            lines.append(f"  {a}")
        lines.append("")

    if summary.get("top_winners"):
        lines.append("TOP WINNERS")
        lines.append("-" * 40)
        for p in summary["top_winners"]:
            lines.append(
                f"  {p['symbol']:>6s}  {p['shares']:.0f} shares  "
                f"${p['current_price']:>8.2f}  P&L: ${p['pnl']:>+8.2f} ({p['pnl_pct']:>+.1f}%)"
            )
        lines.append("")

    if summary.get("top_losers"):
        lines.append("TOP LOSERS")
        lines.append("-" * 40)
        for p in summary["top_losers"]:
            lines.append(
                f"  {p['symbol']:>6s}  {p['shares']:.0f} shares  "
                f"${p['current_price']:>8.2f}  P&L: ${p['pnl']:>+8.2f} ({p['pnl_pct']:>+.1f}%)"
            )
        lines.append("")

    if summary.get("recent_trades"):
        lines.append("RECENT TRADES (last 10)")
        lines.append("-" * 40)
        for t in summary["recent_trades"][:10]:
            sym, action, shares, price, total, ts, reason = t
            lines.append(
                f"  {ts[:16]}  {action.upper():>4s}  {sym:>6s}  "
                f"{shares:.0f} x ${price:.2f} = ${total:.2f}  ({reason})"
            )
        lines.append("")

    lines.append("=" * 60)
    lines.append("  Generated by Kronos Trading Engine")
    lines.append("=" * 60)

    return "\n".join(lines)
